name=EEPROM
version=1.0.0
author=Mitsumine Suzu
maintainer=https://github.com/verylowfreq
sentence=Enables reading and writing to non-volatile storage in the processor.
paragraph=This library uses the FlashROM of the CH32 to emulate EEPROM. EEPROM keeps its content also when the MCU is powered off. The amount of EEPROM available is limited to 256 bytes. Tested with CH32V203.
category=Data Storage
url=http://arduino.cc/en/Reference/EEPROM
architectures=ch32v
